apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: new-py-app-0405 
  janus-idp.io/tekton: new-py-app-0405
  backstage.io/kubernetes-id: new-py-app-0405
  backstage.io/kubernetes-namespace: new-ns 
  app.kubernetes.io/part-of: new-py-app-0405
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  