apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: new-py-app-0405
  janus-idp.io/tekton: new-py-app-0405
  backstage.io/kubernetes-id: new-py-app-0405
  backstage.io/kubernetes-namespace: new-ns 
  app.kubernetes.io/part-of: new-py-app-0405
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml 
