apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: new-py-app-0405
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/yangcao/new-py-app-0405:79b2966cd49ced704f494d2296d57d79f9a63fb5@sha256:e7bfe74352d4293e316215d1aa3fe8c4db4bbaaf1dc2a8adccc1f0f91b1470c1
          name: container-image
